apiVersion: v1
kind: Template
metadata:
  name: cadddy-configmap-template
  annotations:
    description: >- 
      Caddy run time configuration template > 
      this should be created on any namespaces that utilize the devhub deployment"
  labels:
    app: devhub
    type: devhub-template
objects:
- apiVersion: v1
  data:
    Caddyfile: |
      0.0.0.0:2015
      root /var/www/html
      log stdout
      errors stdout
      
      rewrite {
        regexp ^\/topic(\/[\w|\-|\_|~|\.]+)+
        to {path} {path}/ /topic/
      }
      
      gzip {
        ext .js .html .css
      }

      templates {
        ext   .js
      }

      # gatsby_cache_control
      # https://www.gatsbyjs.org/docs/caching/
      header / {
        # prevent any static html from being cached
        Cache-Control "public, max-age=0, must-revalidate"
      }

      header /public/static {
        # all static assets SHOULD be cached
        Cache-Control "public, max-age=31536000, immutable"
      }

      header /public/page-data/ {
        Cache-Control "public, max-age=0, must-revalidate"
      }

      header /app-data.json {
        Cache-Control "public, max-age=0, must-revalidate"
      }
      
      header / {
        # special js file that should not be cached for offline mode
        Cache-Control "public, max-age=0, must-revalidate"
      }
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: ${NAME}-configmap
    labels:
      app: devhub
parameters:
- description: the name of the project, this should be the same name passed into your deployment config
  displayName: The app name
  name: NAME
  required: true

