# docker compose for local development
# this allows for hot reloading of the app
version: '3'
services:
  previewer:
    build: '.'
    image: bcgovimages/devhub-previewer
    env_file:
      - web/.env.production
    volumes:
      - './web/:/site'
      # a hack to ignore node_modules and other folders so that local version,
      # if existing does not mount ontop of the image's version
      - '/site/node_modules/'
      - '/site/.cache/'
      - '/site/public/'
    ports:
      - '8000:8000'
    container_name: devhub-previewer
